// <auto-generated />
using System;
using MarketLab.Infra.Data.EFCore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MarketLab.API.Migrations.MarketLabDb
{
    [DbContext(typeof(MarketLabDbContext))]
    partial class MarketLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MarketLab.Domain.Products.Entitites.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("MarketLab.Domain.Products.Entitites.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MarketLab.Domain.Products.Entitites.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("MarketLab.Domain.Products.Entitites.ProductResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdentifierUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductResources");
                });

            modelBuilder.Entity("MarketLab.Domain.Resources.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://www.kimmarket.com",
                            CreatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 192, DateTimeKind.Local).AddTicks(3780),
                            IsDeleted = false,
                            Name = "Kim",
                            Status = 1,
                            UpdatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(4460)
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://www.bim.com.tr/default.aspx",
                            CreatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6850),
                            IsDeleted = false,
                            Name = "Bim",
                            Status = 1,
                            UpdatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6860)
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://www.a101.com.tr",
                            CreatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6880),
                            IsDeleted = false,
                            Name = "A101",
                            Status = 1,
                            UpdatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6880)
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://www.sokmarket.com.tr/anasayfa",
                            CreatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6880),
                            IsDeleted = false,
                            Name = "Şok",
                            Status = 1,
                            UpdatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6880)
                        },
                        new
                        {
                            Id = 5,
                            BaseUrl = "https://www.migros.com.tr",
                            CreatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6890),
                            IsDeleted = false,
                            Name = "Migros",
                            Status = 1,
                            UpdatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6890)
                        },
                        new
                        {
                            Id = 6,
                            BaseUrl = "https://www.carrefoursa.com/tr",
                            CreatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6890),
                            IsDeleted = false,
                            Name = "Carrefoursa",
                            Status = 1,
                            UpdatedAt = new DateTime(2020, 3, 7, 19, 0, 13, 197, DateTimeKind.Local).AddTicks(6890)
                        });
                });

            modelBuilder.Entity("MarketLab.Domain.Products.Entitites.Product", b =>
                {
                    b.HasOne("MarketLab.Domain.Products.Entitites.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("MarketLab.Domain.Products.Entitites.ProductImage", b =>
                {
                    b.HasOne("MarketLab.Domain.Products.Entitites.Product", null)
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketLab.Domain.Products.Entitites.ProductResource", b =>
                {
                    b.HasOne("MarketLab.Domain.Products.Entitites.Product", "Product")
                        .WithMany("ProductResources")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
